# Autogenerated with SMOP 
from smop.core import *
# ./../matlab/drawBox2D.m

    
@function
def drawBox2D(h=None,box=None,occlusion=None,object_type=None,*args,**kwargs):
    varargin = drawBox2D.varargin
    nargin = drawBox2D.nargin

    # set styles for occlusion and truncation
    occ_col=cellarray(['w','g','y','r'])
# ./../matlab/drawBox2D.m:4
    # show rectangular bounding boxes
    pos=matlabarray(cat(box.x1,box.y1,box.x2 - box.x1 + 1,box.y2 - box.y1 + 1))
# ./../matlab/drawBox2D.m:7
    rectangle('Position',pos,'EdgeColor',occ_col[occlusion + 2],'LineWidth',6,'parent',h[1].axes)
    rectangle('Position',pos,'EdgeColor','k','LineWidth',2,'parent',h[1].axes)
    # plot label
    label_text=sprintf('%s',object_type)
# ./../matlab/drawBox2D.m:13
    x=(box.x1 + box.x2) / 2
# ./../matlab/drawBox2D.m:14
    y=box.y1
# ./../matlab/drawBox2D.m:15
    text(x,max(y - 5,40),label_text,'color',occ_col[occlusion + 2],'BackgroundColor','k','HorizontalAlignment','center','VerticalAlignment','bottom','FontWeight','bold','FontSize',16,'parent',h[1].axes)