# Autogenerated with SMOP 
from smop.core import *
# ./../matlab/drawBox3D.m

    
@function
def drawBox3D(h=None,occlusion=None,corners=None,face_idx=None,orientation=None,*args,**kwargs):
    varargin = drawBox3D.varargin
    nargin = drawBox3D.nargin

    # set styles for occlusion and truncation
    occ_col=cellarray(['w','g','y','r'])
# ./../matlab/drawBox3D.m:4
    # draw projected 3D bounding boxes
    if logical_not(isempty(corners)):
        for f in arange(1,4).reshape(-1):
            line(cat(corners[1,face_idx[f,:]],corners[1,face_idx[f,1]]) + 1,cat(corners[2,face_idx[f,:]],corners[2,face_idx[f,1]]) + 1,'parent',h[2].axes,'color',occ_col[occlusion + 2],'LineWidth',6)
            line(cat(corners[1,face_idx[f,:]],corners[1,face_idx[f,1]]) + 1,cat(corners[2,face_idx[f,:]],corners[2,face_idx[f,1]]) + 1,'parent',h[2].axes,'color','k','LineWidth',2)
    
    # draw orientation vector
    if logical_not(isempty(orientation)):
        line(cat(orientation[1,:],orientation[1,:]) + 1,cat(orientation[2,:],orientation[2,:]) + 1,'parent',h[2].axes,'color','w','LineWidth',6)
        line(cat(orientation[1,:],orientation[1,:]) + 1,cat(orientation[2,:],orientation[2,:]) + 1,'parent',h[2].axes,'color','k','LineWidth',2)
    