notifications:
  email: false
sudo: required
language: python
python:
  - "3.4"
  - "3.5"

install:
  - sudo apt-get install python3-pip python3-dev
  - pip3 install tensorflow
  - pip3 install -r requirements.txt


before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - python tests/GanTest.py
