# Autogenerated with SMOP 
from smop.core import *
# /opt/project/devkit/matlab/project.m

    
@function
def project(p_in=None,T=None,*args,**kwargs):
    varargin = project.varargin
    nargin = project.nargin

    # dimension of data and projection matrix
    dim_norm=size(T,1)
# /opt/project/devkit/matlab/project.m:4
    dim_proj=size(T,2)
# /opt/project/devkit/matlab/project.m:5
    # do transformation in homogenuous coordinates
    p2_in=copy(p_in)
# /opt/project/devkit/matlab/project.m:8
    if size(p2_in,2) < dim_proj:
        p2_in[:,dim_proj]=1
# /opt/project/devkit/matlab/project.m:10
    
    p2_out=(dot(T,p2_in.T)).T
# /opt/project/devkit/matlab/project.m:12
    # normalize homogeneous coordinates:
    p_out=p2_out[:,1:dim_norm - 1] / (dot(p2_out[:,dim_norm],ones(1,dim_norm - 1)))
# /opt/project/devkit/matlab/project.m:15