FROM tensorflow/tensorflow:latest-py3

RUN apt-get update && \
    apt-get install -y \
        python3-tk

RUN pip install --upgrade setuptools pip
RUN pip install \
    numpy \
    scikit-learn \
    scipy \
    matplotlib \
    keras
